server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        same-site: lax
        max-age: 1800
      timeout: 30m
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=app_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  session:
    redis:
      namespace: spring:session
      flush-mode: on_save
      save-mode: on_set_attribute